name: flutterfrontend
description: "Monaco RFID Front end"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_datawedge: ^3.0.0
  go_router: ^14.3.0
  zeta_flutter: ^0.17.0
  flutter_svg: ^2.0.11
  http: ^1.2.2
  provider: ^6.1.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: F1
      fonts:
        - asset: lib/assets/F1-display-regular.ttf
        - asset: lib/assets/F1-display-bold.ttf
          weight: 700
        - asset: lib/assets/F1-display-wide.ttf
          weight: 800
    - family: Titillium
      fonts:
        - asset: lib/assets/Titillium-Regular.ttf
        - asset: lib/assets/Titillium-Bold.ttf
          weight: 700
        - asset: lib/assets/Titillium-Light.ttf
          weight: 300
        - asset: lib/assets/Titillium-SemiBold.ttf
          weight: 600

  assets:
    - lib/assets/
