version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: marcdb
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: marcpwd
    # volumes:
    #   - db-data:/var/lib/postgresql/data
  app:
    image: my-node-app
    ports:
      - 13000:3000
    # build: .
    # ports:
    #   - "5000:5000"
    # depends_on:
    #   - db
    # environment:
    #   DATABASE_URL: postgresql://marc:marcpwd@db:5432/marcdb