version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    image: my-node-app
    ports:
      - 13000:3000
    environment:
      RFID_ADDRESS: ${RFID_ADDRESS}
      WEB_PASSWORD: ${WEB_PASSWORD}
      WEB_USERNAME: ${WEB_USERNAME}