### Set up the database (only run once per device)
GET http://localhost:13000/setup
### Start RFID
GET http://localhost:13000/start
### Stop RFID
GET http://localhost:13000/stop
### Get all rows from the database
GET http://localhost:13000

### POST fastest lap time
POST http://localhost:13000/lap
Content-Type: application/json
  
  {
    "lap_time": "18:00.001",
    "overall_time": "100:00.001",
  }

### Scan into system after storing this, required by websocket
POST http://localhost:13000/scanUser
Content-Type: application/json
  
  {
    "name": "Marc Adlington 2",
    "id": "453456123"
  }

### Get individual leaderboard
GET http://localhost:13000/getLeaderboard

### Get team leaderboard
GET http://localhost:13000/getTeamLeaderboard

### Get individual overall time leaderboard
GET http://localhost:13000/getOverallLeaderboard

### Get current scanned in user and their lap data
GET http://localhost:13000/getUser

### DELETE ALL ENTRIES 
GET http://localhost:13000/removeAllEntries

### DELETE DB Structure 
GET http://localhost:13000/removeTableFromDb



### POST RFID data
POST http://localhost:13000/rfid
Content-Type: application/json

[  
  {
    "timestamp":"2024-11-15T19:58:40",
    "data":{
      "idHex": "00000000000001"
    }
  }
]


### POST Status
POST http://localhost:13000/status
Content-Type: application/json

  {
    "status":3
  }

### PUT Lights
POST http://localhost:13000/lights

### POST fake lap
POST http://localhost:13000/fakeLaps
