### Set up the database (only run once per device)
GET http://localhost:13000/setup
### Start RFID
GET http://localhost:13000/start
### Stop RFID
GET http://localhost:13000/stop
### Get all rows from the database
GET http://localhost:13000

### POST fastest lap time
POST http://localhost:13000/lap
Content-Type: application/json
  
  {
    "lap_time": "18:00.001"
  }

### Scan into system after storing this, required by websocket
POST http://localhost:13000/scanUser
Content-Type: application/json
  
  {
    "name": "Marc Adlington 2",
    "id": "45345rrrwr6123"
  }

### Get individual leaderboard
GET http://localhost:13000/getLeaderboard

### Get team leaderboard
GET http://localhost:13000/getTeamLeaderboard

### Get current scanned in user and their lap data
GET http://localhost:13000/getUser

### DELETE ALL ENTRIES 
GET http://localhost:13000/removeAllEntries

### DELETE DB Structure 
GET http://localhost:13000/removeTableFromDb

